spring:
  redis:
    host: 127.0.0.1
    port: 16379
    database: 0
    password:

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: true # 暂时不开启
  port: 8879

jwt:
  accessToken:
    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致
